apiVersion: apps/v1
kind: Deployment
metadata:
  name: applytics-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applytics
  template:
    metadata:
      labels:
        app: applytics
    spec:
      containers:
      - name: frontend
        image: us-west1-docker.pkg.dev/seng401-applytics-345415/frontend-repo/frontend-gke:latest
        ports:
        - containerPort: 3000
      - name: login
        image: us-west1-docker.pkg.dev/seng401-applytics-345415/login-repo/login-gke:latest
        ports:
        - containerPort: 5000
      - name: ml
        image: us-west1-docker.pkg.dev/seng401-applytics-345415/ml-repo/ml-gke:latest
        ports:
        - containerPort: 5010
      - name: review
        image: us-west1-docker.pkg.dev/seng401-applytics-345415/review-repo/review-gke:latest
        ports:
        - containerPort: 5020