apiVersion: v1
kind: Service
metadata:
    name: tologin
    labels:
        name: comms
        app: applytics
spec:
    ports:
    - port: 5000
      targetPort: 5000
    selector:
        app: applytics